export { addChannel } from './addChannel'
export { proceedChannelSuggestion } from './proceedChannelSuggestion'
export { removeChannel } from './removeChannel'
export { addFeaturedChannel } from './addFeaturedChannel'
export { removeFeaturedChannel } from './removeFeaturedChannel'
export { getFeaturedChannel } from './getFeaturedChannel'
