services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: memesearch-elastic
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: true
      path.repo: ./backup
      xpack.security.transport.ssl.enabled: true
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/elastic-certificates.key
      xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/elastic-certificates.crt
      xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/elastic-stack-ca.pem
      # cluster.routing.allocation.disk.threshold_enabled: false
    mem_limit: 10GB
    ports:
      - 9200:9200
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
      - ./backup/elastic/:/usr/share/elasticsearch/backup/elastic/
      - ./certs:/usr/share/elasticsearch/config/certs

  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    container_name: memesearch-rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia

  loki:
    image: grafana/loki
    container_name: loki
    hostname: loki
    restart: unless-stopped
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./configs/loki.yaml:/etc/loki/local-config.yaml
      - ./data/loki/chunks:/loki/chunks

  promtail:
    image: grafana/promtail
    container_name: promtail
    hostname: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/docker-config.yaml
    volumes:
      - ./data/promtail:/var/lib/promtail
      - ./configs/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/log
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./data/grafana:/var/lib/grafana
      # - ./data/grafana/conf:/etc/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki

  mysql:
    image: mariadb:11.1
    container_name: memesearch-mysql
    restart: unless-stopped
    ports:
      - "127.0.0.1:9507:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_AUTO_UPGRADE: 'yes'
      TZ: 'Asia/Tbilisi'
    env_file:
      - ./.mysql.env
    command:
     - --skip-grant-tables
     - --innodb-buffer-pool-size=128M
     - --wait_timeout=65

  nlp:
    container_name: nlp
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      AMQP_ENDPOINT: 'amqp://rabbitmq:5672'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/nlp/nltk_data:/root/nltk_data
    depends_on:
      - rabbitmq

  # Extended containers

  telegram-api-server:
    container_name: api
    extends:
      file: ../TelegramApiServer/docker-compose.yml
      service: api
    env_file:
      - ../TelegramApiServer/.env.docker
      - ./.env
      - ./.mysql.env
    depends_on:
      - mysql

  telegram-rss:
    container_name: memesearch-telegram-rss
    extends:
      file: ../TelegramRSS/docker-compose.yml
      service: telegram-rss
    depends_on:
      - telegram-api-server

networks:
  default:
    driver: bridge
    name: memesearch
