type EnvKeys =
| 'TG_API_ENDPOINT'
| 'TG_RSS_ENDPOINT'
| 'OCR_SPACE_API_KEYS'
| 'OCR_SPACE_API_KEYS_PRO'
| 'CYCLE_SLEEP_TIMEOUT'
| 'ELASTIC_ENDPOINT'
| 'ELASTIC_USERNAME'
| 'ELASTIC_PASSWORD'
| 'AMQP_ENDPOINT'
| 'AMQP_MEMES_TO_NLP_CHANNEL'
| 'AMQP_NLP_TO_PUBLISHER_CHANNEL'
| 'TELEGRAM_API_ID'
| 'TELEGRAM_API_HASH'
| 'TELEGRAM_BOT_TOKEN'
| 'TELEGRAM_BOT_WEBHOOK_PATH'
| 'TELEGRAM_BOT_PREMIUM_COST_1M'
| 'TELEGRAM_BOT_PREMIUM_COST_3M'
| 'TELEGRAM_BOT_PREMIUM_COST_12M'
| 'TELEGRAM_PUBLISHER_BOT_TOKEN'
| 'TELEGRAM_PUBLISHER_BOT_WEBHOOK_PATH'
| 'CRYPTOPAY_BOT_TEST_TOKEN'
| 'CRYPTOPAY_BOT_TEST_WEBHOOK_PATH'
| 'MEMEPLEX_WEBSITE_DOMAIN'
| 'MEMEPLEX_ADMIN_PASSWORD'
| 'MEMEPLEX_MODERATOR_PASSWORD'
| 'GF_SECURITY_ADMIN_PASSWORD'
| 'GF_SECURITY_ADMIN_USER'
| 'DB_HOST'
| 'DB_PORT'
| 'DB_USER'
| 'DB_PASSWORD'
| 'DB_DATABASE'

declare global {
  namespace NodeJS {
    interface ProcessEnv extends Record<EnvKeys, string> {
      ENVIRONMENT?: 'TESTING' | 'DEVELOPMENT' | 'PRODUCTION'
      GF_AUTH_ANONYMOUS_ENABLED?: string
      GF_AUTH_ANONYMOUS_ORG_ROLE?: string
      GF_AUTH_DISABLE_LOGIN_FORM?: string
    }
  }
}

export {}
