apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
  - name: ElasticSearch
    type: elasticsearch
    access: proxy
    url: http://memesearch-elastic:9200
    jsonData:
      index: image_text
      timeField: timestamp
    basicAuth: true
    secureJsonData:
      basicAuthUser: ${ELASTIC_USERNAME}
      basicAuthPassword: ${ELASTIC_PASSWORD}
  - name: MySQL
    type: mysql
    url: mysql:3306
    user: root
    jsonData:
      database: MadelineProto
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
