{
 "title": "container-logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "ElasticSearch",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"memesearch-elastic\"}"
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"memesearch-rabbitmq\"} |= ``"
    }
   ]
  },
  {
   "title": "TelegramApiServer",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"api\"} |= ``"
    }
   ]
  },
  {
   "title": "TelegramRSS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"memesearch-telegram-rss\"} |= ``"
    }
   ]
  },
  {
   "title": "Service logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"services\"} |= ``"
    }
   ]
  }
 ]
}