export enum EState {
  ADD_CHANNEL = 'ADD_CHANNEL',
  ADD_KEYWORDS = 'ADD_KEYWORDS',
  CHANNEL_SELECT = 'CHANNEL_SELECT',
  CHANNEL_SETTINGS = 'CHANNEL_SETTINGS',
  KEYWORD_SETTINGS = 'KEYWORD_SETTINGS',
  MAIN = 'start'
}
