{
 "title": "MemeSearch",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hourly Meme Inflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AMQP Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{amqp=\"queue\"} |= ``"
    }
   ]
  },
  {
   "title": "Meme Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "date", "id": "2", "settings": { "interval": "1y" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Bot users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT COUNT(*) as Pics FROM MadelineProto.bot_users"
    },
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT COUNT(*) as Inline FROM MadelineProto.bot_inline_users"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT COUNT(*) as Active FROM MadelineProto.channels WHERE status is NULL"
    },
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT COUNT(*) as Suggested FROM MadelineProto.channel_suggestions WHERE processed IS NULL"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT\n  COUNT(*) AS total,\n  COUNT(CASE WHEN anonymity IN ('anonymous', 'elite') THEN 1 END) AS anonymous,\n  COUNT(CASE WHEN ocr_key IS NOT NULL THEN 1 END) as with_key,\n  COUNT(CASE WHEN availability = 1 AND anonymity IN ('anonymous', 'elite') THEN 1 END) AS available,\n  COUNT(CASE WHEN ocr_key IS NOT NULL AND availability = 1 AND anonymity IN ('anonymous', 'elite') THEN 1 END) as available_with_key\nFROM\n  MadelineProto.proxies;\n"
    }
   ]
  },
  {
   "title": "Service errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"services\"}"
    }
   ]
  },
  {
   "title": "OCR keys",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT\n  'free' AS plan,\n  COUNT(*) AS total,\n  COUNT(CASE WHEN timeout IS NULL OR timeout < DATE_ADD(NOW(), INTERVAL 30 MINUTE) THEN 1 END) AS without_timeout,\n  MIN(timeout) AS oldest_timeout\nFROM\n  MadelineProto.ocr_keys\nUNION ALL\nSELECT\n  'pro' AS plan,\n  COUNT(*) AS total,\n  COUNT(CASE WHEN timeout IS NULL OR timeout < DATE_ADD(NOW(), INTERVAL 30 MINUTE) THEN 1 END) AS without_timeout,\n  MIN(timeout) AS oldest_timeout\nFROM\n  MadelineProto.ocr_keys_pro;\n"
    }
   ]
  },
  {
   "title": "Invoices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT COUNT(*) as Paid FROM MadelineProto.bot_invoices WHERE status = 'paid'"
    },
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT COUNT(*) as Active FROM MadelineProto.bot_invoices WHERE status = 'active'"
    },
    {
     "dataset": "MadelineProto",
     "rawSql": "SELECT COUNT(*) as Expired FROM MadelineProto.bot_invoices WHERE status = 'expired'"
    }
   ]
  },
  {
   "title": "Bot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memes published",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "MadelineProto",
       "rawSql": "SELECT COUNT(*) FROM MadelineProto.bot_actions WHERE action = 'meme_post' LIMIT 50 "
      }
     ]
    },
    {
     "title": "Daily activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 3, "y": 24 },
     "targets": [
      {
       "dataset": "MadelineProto",
       "rawSql": "SELECT\n  FROM_UNIXTIME(timestamp, '%Y-%m-%d 00:00:00') as timestamp,\n  COUNT(action) as actions,\n  SUM(action = 'meme_post') AS meme_post,\n  user_id as users\nFROM MadelineProto.bot_actions\nGROUP BY timestamp"
      },
      {
       "dataset": "MadelineProto",
       "rawSql": "SELECT\n  FROM_UNIXTIME(timestamp, '%Y-%m-%d 00:00:00') as timestamp,\n  COUNT(action) as inline_actions,\n  SUM(action = 'select') AS inline_select,\n  user_id as inline_users\nFROM MadelineProto.bot_inline_actions\nGROUP BY timestamp"
      }
     ]
    },
    {
     "title": "Hourly activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
     "targets": [
      {
       "dataset": "MadelineProto",
       "rawSql": "SELECT\n  FROM_UNIXTIME(timestamp, '%Y-%m-%d %H:00:00') as timestamp,\n  COUNT(action) as actions,\n  SUM(action = 'meme_post') AS meme_post,\n  user_id as users\nFROM MadelineProto.bot_actions\nGROUP BY timestamp"
      },
      {
       "dataset": "MadelineProto",
       "rawSql": "SELECT\n  FROM_UNIXTIME(timestamp, '%Y-%m-%d%H:00:00') as timestamp,\n  COUNT(action) as inline_actions,\n  SUM(action = 'select') AS inline_select,\n  user_id as inline_users\nFROM MadelineProto.bot_inline_actions\nGROUP BY timestamp"
      }
     ]
    },
    {
     "title": "Pics",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/tg-bot.log\"} |= ``"
      }
     ]
    },
    {
     "title": "CryptoPay",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/cryptopay-bot.log\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "ocr",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/ocr.log\"} |= ``"
      }
     ]
    },
    {
     "title": "downloader",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/downloader.log\"} |= ``"
      }
     ]
    },
    {
     "title": "tg-parser",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/tg-parser.log\"} |= ``"
      }
     ]
    },
    {
     "title": "web",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/web.log\"} |= ``"
      }
     ]
    },
    {
     "title": "proxy-checker",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/proxy-checker.log\"} |= ``"
      }
     ]
    },
    {
     "title": "web admin",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/web-admin.log\"} |= ``"
      }
     ]
    },
    {
     "title": "proxy-finder",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/proxy-finder.log\"} |= ``"
      }
     ]
    },
    {
     "title": "ElasticSearch entities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "ElasticSearch",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "{container=\"memesearch-elastic\"}"
      }
     ]
    },
    {
     "title": "RabbitMQ",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "expr": "{container=\"memesearch-rabbitmq\"} |= ``"
      }
     ]
    },
    {
     "title": "TelegramApiServer",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "{container=\"api\"} |= ``"
      }
     ]
    },
    {
     "title": "TelegramRSS",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "expr": "{container=\"memesearch-telegram-rss\"} |= ``"
      }
     ]
    },
    {
     "title": "Mysql",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "{container=\"memesearch-mysql\"} |= ``"
      }
     ]
    },
    {
     "title": "NLP",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "targets": [
      {
       "expr": "{container=\"nlp\"} |= `` | logfmt"
      }
     ]
    },
    {
     "title": "Grafana",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "targets": [
      {
       "expr": "{container=\"grafana\"} |= ``"
      }
     ]
    },
    {
     "title": "Loki",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "targets": [
      {
       "expr": "{container=\"loki\"} |= ``"
      }
     ]
    },
    {
     "title": "Alloy",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "{container=\"alloy\"} |= `` | logfmt"
      }
     ]
    }
   ]
  }
 ]
}